import image from "../assets/images/admin photo.jpg";

const descriptionText =
  "Milli Aviasiya Akademiyasının təşkilatçılığı ilə həyata keçirilmiş “Pilotsuz Sistemlər: Süni İntellekt, Dizayn və Səmərəlilik” (“International Symposium on Unmanned Systems: AI, Design and Efficiency” - ISUDEF’24) beynəlxalq simpoziumunun materiallar toplusu nüfuzlu Springer Nature nəşriyyatının “Sustainable Aviation” kitab seriyasında “Research and Updates on the Use of Artificial Intelligence in Drone Technology” adı ilə dərc olunub. Bu toplu pilotsuz sistemlər, süni intellekt və aviasiya texnologiyaları sahəsində aparılan ən son elmi tədqiqatları əhatə edir. Topluda yer alan elmi məqalələr Scopus bazasında indekslənəcək və Akademiyanın alim və tədqiqatçılarının beynəlxalq səviyyədə tanınması imkanlarını daha da artıracaq. Kitabla tanış olmaq üçün keçid etməyi unutmayın.";

export const mockPosts = [
  {
    id: 1,
    title:
      "Milli Aviasiya Akademiyasının təşkilatçılığı ilə həyata keçirilən tədbir",
    image,
    type: "News",
    date: "06/11/2026",
    time: "10:19 AM",
    status: "Active",
    publishStatus: "Publish",
    author: "snovruzlu",
    desc: descriptionText,
  },
  {
    id: 2,
    title: "Milli Aviasiya Akademiyasının Akademiyasında keçirilən görüş",
    image,
    type: "Announcement",
    date: "06/11/2026",
    time: "10:19 AM",
    status: "Inactive",
    publishStatus: "Publish",
    author: "snovruzlu",
    desc: descriptionText,
  },
  {
    id: 3,
    title:
      "Milli Aviasiya Akademiyasının təşkilatçılığı ilə həyata keçirilən tədbir",
    image,
    type: "News",
    date: "06/11/2026",
    time: "10:19 AM",
    status: "Active",
    publishStatus: "Publish",
    author: "snovruzlu",
    desc: descriptionText,
  },
  {
    id: 4,
    title: "Milli Aviasiya Akademiyasının Akademiyasında keçirilən görüş",
    image,
    type: "Announcement",
    date: "06/11/2026",
    time: "10:19 AM",
    status: "Inactive",
    publishStatus: "Publish",
    author: "snovruzlu",
    desc: descriptionText,
  },
  {
    id: 5,
    title:
      "Milli Aviasiya Akademiyasının təşkilatçılığı ilə həyata keçirilən tədbir",
    image,
    type: "News",
    date: "06/11/2026",
    time: "10:19 AM",
    status: "Active",
    publishStatus: "Publish",
    author: "snovruzlu",
    desc: descriptionText,
  },
  {
    id: 6,
    title: "Milli Aviasiya Akademiyasının Akademiyasında keçirilən görüş",
    image,
    type: "Announcement",
    date: "06/11/2026",
    time: "10:19 AM",
    status: "Inactive",
    publishStatus: "Publish",
    author: "snovruzlu",
    desc: descriptionText,
  },
  {
    id: 7,
    title: "Milli Aviasiya Akademiyasının təşkilatçılığı ilə",
    image,
    type: "News",
    date: "06/11/2026",
    time: "10:19 AM",
    status: "Active",
    publishStatus: "Publish",
    author: "snovruzlu",
    desc: descriptionText,
  },
  {
    id: 8,
    title: "Milli Aviasiya Akademiyasının Akademiyasında keçirilən görüş",
    image,
    type: "Announcement",
    date: "06/11/2026",
    time: "10:19 AM",
    status: "Inactive",
    publishStatus: "Publish",
    author: "snovruzlu",
    desc: descriptionText,
  },
  {
    id: 9,
    title:
      "Milli Aviasiya Akademiyasının təşkilatçılığı ilə həyata keçirilən tədbir",
    image,
    type: "News",
    date: "06/11/2026",
    time: "10:19 AM",
    status: "Active",
    publishStatus: "Publish",
    author: "snovruzlu",
    desc: descriptionText,
  },
  {
    id: 10,
    title: "Milli Aviasiya Akademiyasının Akademiyasında keçirilən görüş",
    image,
    type: "Announcement",
    date: "06/11/2026",
    time: "10:19 AM",
    status: "Inactive",
    publishStatus: "Publish",
    author: "snovruzlu",
    desc: descriptionText,
  },
  {
    id: 11,
    title:
      "Milli Aviasiya Akademiyasının təşkilatçılığı ilə həyata keçirilən search test tədbir",
    image,
    type: "News",
    date: "06/11/2026",
    time: "10:19 AM",
    status: "Active",
    publishStatus: "Publish",
    author: "snovruzlu",
    desc: descriptionText,
  },
  {
    id: 12,
    title: "Milli Aviasiya Akademiyasının Akademiyasında keçirilən görüş",
    image,
    type: "Announcement",
    date: "06/11/2026",
    time: "10:19 AM",
    status: "Inactive",
    publishStatus: "Publish",
    author: "snovruzlu",
    desc: descriptionText,
  },
  {
    id: 13,
    title:
      "Milli Aviasiya Akademiyasının təşkilatçılığı ilə həyata keçirilən tədbir",
    image,
    type: "News",
    date: "06/11/2026",
    time: "10:19 AM",
    status: "Inactive",
    publishStatus: "Publish",
    author: "snovruzlu",
    desc: descriptionText,
  },
  {
    id: 14,
    title:
      "Milli Aviasiya Akademiyasının Akademiyasında keçirilən görüş, search test",
    image,
    type: "Announcement",
    date: "06/11/2026",
    time: "10:19 AM",
    status: "Active",
    publishStatus: "Publish",
    author: "snovruzlu",
    desc: descriptionText,
  },
];
